### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by eviau** [MMinkova/git-physical#1]
Hello,

I was not sure how to get in touch, so I decided to open an issue.

I am planning on giving workshops about git, for digital artists. I really like the idea of a git analogue workshop and I was wondering if it would be possible to use some of the materials (at least as an inspiration!) for my workshop :) 

I saw no license - this is why I am asking.

Also, no hurry to answer - I am still in the planning phase.

Let me know,
Edith

**Comment by MMinkova** [comment]
Hi,
Thanks for getting in touch. I have just added a license to the repo.
Hope you find the contents useful.

Best,
MM

**Comment by eviau** [comment]
Thank you !
